#!/usr/bin/env python3
import sys


def main():
    regs = []

    for line in sys.stdin:
        line = line.strip()
        parts = line.split(' ')
        if line.endswith('(GP_LVL)') or line.endswith('(GP_LVL2)') or line.endswith('(GPIO_LVL3)'):
            val = parts[1]
            regs.append(int(val, 16))

    if not regs:
        raise Exception("regs is empty")

    for k, reg in enumerate(regs):
        for i in range(32):
            gpio_num = (32 * k) + i
            if gpio_num > 75:
                break
            bit = gpio_num % 32
            gpio_val = (reg >> bit) & 1
            print("GPIO%d = %d" % (gpio_num, gpio_val))


if __name__ == '__main__':
    main()
